#█████████████████████████████████████████████████████
#█───██───██────██─██─██───██───██────██───██─█─██───█
#█─█████─███─█████──█─██─█████─███─██─███─███─█─██─███
#█───███─███─█──██─█──██───███─███────███─███─█─██───█
#███─███─███─██─██─██─████─███─███─██─███─███─█─████─█
#█───██───██────██─██─██───███─███─██─███─███───██───█
#█████████████████████████████████████████████████████

#Time to refresh signs. Default: 1 second.
time: 1